#define ChargeDistribution_cxx
#include <TStyle.h>
#include <sstream>
#include <string.h>
#include <vector>
#include <iostream>
#include <cstdlib>
#include <fstream>
#include <utility>
#include <stdio.h>
#include <TCanvas.h>
#include <TSpectrum.h>
#include "TFile.h"
#include <TF1.h>
#include "TInterpreter.h"
#include <TStyle.h>
#include "TTree.h"
#include "TMath.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TGraph.h"
#include "ChargeDistribution.h"
using namespace std;
using namespace RICHsystem;
class RootConvert;

void RootConvert::Loop2(TTree *signaltree, TTree *bkgtree, double threshold){}
void RootConvert::Loop3(char *RootFileName, double threshold){}

void RootConvert::Loop(char *RootFileName){
    //this function read especially the data from DOUBLE REUSED CHANNEL test
    //for 2 boards(15 and 31), each of their channels(68 x channels and 68 y channels) is connected to two AGET chips with a chosen capacitor
    //i.e. NO.0 and NO.2 chip of each board has the same original sinal, so do NO.1 and NO.3
    //so for each detector channel, a 2D histogram is drawn to show the correlation with two different readout signals
    string RFile = "./charge_test/chargedistribution11_23.root";
    cout<<"Output files:"<<endl;
    cout<<RFile<<"\n"<<endl;

    TFile *outFile=new TFile(RFile.c_str(),"UPDATE");     //open the root file in update mode
    TH2F *histped[Nfec][2][Nch];

    for (int f=0;f<Nfec;f++){                         //create and name the histograms of each channel by its fec, chip and channel
      for (int c=0;c<2;c++){
        for (int h=0;h<Nch;h++){
          char cc[60];
          memset(cc,0,sizeof(cc));
          sprintf(cc,"FEC%02d_Chip%02d_Chn%02d_pedestal",f,c,h);      //set the name of the histogram
          if(outFile->Get(cc)){
            histped[f][c][h] = (TH2F*)outFile->Get(cc);
          }
          else{
            histped[f][c][h] = new TH2F(cc,";channel of Chip 0/1;channel of Chip 2/3",1000,0,1000,1000,0,1000);
          }
        }
      }
    }
    
    //Notice:This pedestal file is NOT the txt file generated by Pedestal.C. It should be generated by other ways
    //Also, during different tests, the pedestal file should be changed
    char pedestaldata[80] ="./Calibration/noise_11_23_1pC.txt";
    LoadPedestal(pedestaldata);

    //new mapL2
    std::map <Int_t, Int_t> mapL2;
    mapL2.insert(pair<Int_t, Int_t>(31, 0));                    //fec 31--->tag 0
    mapL2.insert(pair<Int_t, Int_t>(15, 1));                    //fec 15--->tag 1
    
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //Loop start
    cout<<"Loop Root File..."<<endl;
    if (fChain == 0) return;
    Long64_t nentries = fChain->GetEntriesFast();
    cout<<"~~~~~~~~~~~~~~~"<<endl;
    cout<<"Nentries:"<<nentries<<endl;
    Long64_t ientry;

    double pedM[2];

    for (Long64_t jentry=0; jentry<nentries;jentry++){
      ientry = LoadTree(jentry);
      if (ientry < 0) break;
      fChain->GetEntry(jentry);
      //loop entries
      if(jentry%((int)(nentries/10.))==0){
          // cout<<"Events:"<<jentry<<"("<<(int)(jentry*100./nentries)<<"%)"<<endl;
          cout<<"Events:"<<jentry<<endl;
      }

      for(int i=0; i<nHits;i++){
        pedM[0] = pedestal[mapL2[Fec[i]]][Chip[i]][Chn[i]][0];                    //mean is the 4th column of pedestal file
        if(Chip[i]==0){
          //Loop to find the signal corresponding to the same detector channel
          for(int j=0;j<nHits;j++){
            if(Fec[j]==Fec[i] && Chip[j]==2 && Chn[j]==Chn[i]){
              pedM[1] = pedestal[mapL2[Fec[j]]][Chip[j]][Chn[j]][0];
              histped[mapL2[Fec[i]]][Chip[i]][Chn[i]]->Fill(maxADC[i]-pedM[0], maxADC[j]-pedM[1]);
              break;
            }
          }
        }
        else if(Chip[i]==1){
          //Loop to find the signal corresponding to the same detector channel
          for(int j=0;j<nHits;j++){
            if(Fec[j]==Fec[i] && Chip[j]==3 && Chn[j]==Chn[i]){
              pedM[1] = pedestal[mapL2[Fec[j]]][Chip[j]][Chn[j]][0];
              histped[mapL2[Fec[i]]][Chip[i]][Chn[i]]->Fill(maxADC[i]-pedM[0], maxADC[j]-pedM[1]);
              break;
            }
          }
        }
        else  continue;
      }
    }

    //Loop end
    cout<<"Loop end!\n"<<endl;

    ofstream paras;
    string TXTFILE = "./charge_test/fit_parameters_11_23.txt";
    paras.open(TXTFILE.c_str());
    double par[2];
    TF1 *PedFit=new TF1("PedFit","pol1");
    TH1F* slop_hist = new TH1F("slop distribution", ";slop;counts",20,0.9,1.1);
    //Write all the histograms to the root file
    //outFile->Write();       //this is dangerous!!!!
    gStyle->SetOptFit(1111);
    gStyle->SetOptStat(111);
    for (int f=0;f<Nfec;f++){
      for (int c=0;c<2;c++){
        for (int h=0;h<Nch;h++){
          memset(par,0,sizeof(par));
          if(histped[f][c][h]->GetEntries()>100) {
            histped[f][c][h]->Fit(PedFit);
            PedFit->GetParameters(par);
            slop_hist->Fill(par[1]);
          }
          histped[f][c][h]->Write();
          paras<<f<<"\t"<<c<<"\t"<<h<<"\t"<<par[0]<<"\t"<<par[1]<<std::endl;           //write fec, chip no, channel no, fit parameters into the .txt file
        }
      }
    }
    slop_hist->Write();
    outFile->Close();
    paras.close();
}

//define main()
string filename;
void helpinfo(){

  cout<<"Usage is ./ChargeDistribution_exe ./Raw2ROOT/<filename>\n";
  cout<<"default output file name is <./chargedistribution.root>"<<endl;	
  return;
} 
void phrase_command(int argc,char *argv[]){
  if (argc<2){ helpinfo();
    exit(0);
  }else {filename=(string) argv[1]; cout<<"START\n~~~~~*****~~~~~\nInput File : "<<filename<<endl;}
}

int main(int argc,char *argv[])
{

  phrase_command(argc,argv);
  string Tt="richraw";
  const char *TtreeName=(char *)(Tt.data());
  const Text_t* RawRootFile=(Text_t*)(filename.data());
  char *RawRootFile_c=(char *)(filename.data());
  TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject(RawRootFile);
  if (!f) 
    {
      f = new TFile(RawRootFile_c);
     }
  TTree *tree = (TTree*)gDirectory->Get(TtreeName);
 
  RootConvert xx;
  xx.RootConvert::Init(tree);
  xx.RootConvert::Loop(RawRootFile_c);
    cout<<"\n~~~~~*****~~~~~\nTHE END"<<endl;
  return 1;

} 